//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShakes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeShakes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CoffeeCup {
            get {
                object obj = ResourceManager.GetObject("CoffeeCup", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear50 {
            get {
                object obj = ResourceManager.GetObject("gear50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------.
        /// </summary>
        internal static string mnu_Break {
            get {
                return ResourceManager.GetString("mnu-Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter.
        /// </summary>
        internal static string mnu_Jitter {
            get {
                return ResourceManager.GetString("mnu-Jitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax.
        /// </summary>
        internal static string mnu_Relax {
            get {
                return ResourceManager.GetString("mnu-Relax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting there.....
        /// </summary>
        internal static string txt_AlmostZen {
            get {
                return ResourceManager.GetString("txt-AlmostZen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the Jitters?.
        /// </summary>
        internal static string txt_GetJitters {
            get {
                return ResourceManager.GetString("txt-GetJitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_NotZen {
            get {
                return ResourceManager.GetString("txt-NotZen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whew! Lets go ahead and chill out. .
        /// </summary>
        internal static string txt_StopJitters {
            get {
                return ResourceManager.GetString("txt-StopJitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenned out.
        /// </summary>
        internal static string txt_Zen {
            get {
                return ResourceManager.GetString("txt-Zen", resourceCulture);
            }
        }
    }
}
